// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VerbTrainer.Infrastructure.Data;

#nullable disable

namespace VerbTrainer.Migrations
{
    [DbContext(typeof(VerbTrainerDbContext))]
    [Migration("20230918072515_RefactorDeckView")]
    partial class RefactorDeckView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Binyan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Binyanim");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Conjugation", b =>
                {
                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.Property<int>("TenseId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VerbId", "TenseId");

                    b.HasIndex("TenseId");

                    b.ToTable("Conjugations");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.DeckVerb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int>("VerbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("VerbId");

                    b.ToTable("DeckVerbs");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Tense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenses");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Verb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BinyanId")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BinyanId");

                    b.ToTable("Verbs");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Conjugation", b =>
                {
                    b.HasOne("VerbTrainer.Infrastructure.Data.Models.Hebrew.Tense", "Tense")
                        .WithMany()
                        .HasForeignKey("TenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerbTrainer.Infrastructure.Data.Models.Hebrew.Verb", "Verb")
                        .WithMany("Conjugations")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tense");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.DeckVerb", b =>
                {
                    b.HasOne("VerbTrainer.Infrastructure.Data.Models.Hebrew.Deck", "Deck")
                        .WithMany("DeckVerbs")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VerbTrainer.Infrastructure.Data.Models.Hebrew.Verb", "Verb")
                        .WithMany("DeckVerbs")
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Verb", b =>
                {
                    b.HasOne("VerbTrainer.Infrastructure.Data.Models.Hebrew.Binyan", "Binyan")
                        .WithMany("Verbs")
                        .HasForeignKey("BinyanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Binyan");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Binyan", b =>
                {
                    b.Navigation("Verbs");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Deck", b =>
                {
                    b.Navigation("DeckVerbs");
                });

            modelBuilder.Entity("VerbTrainer.Infrastructure.Data.Models.Hebrew.Verb", b =>
                {
                    b.Navigation("Conjugations");

                    b.Navigation("DeckVerbs");
                });
#pragma warning restore 612, 618
        }
    }
}
